TheRat\OmCms\AdminBundle\Entity\User\User:
    type: entity
    table: fos_user_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
