<?php

namespace TheRat\OmCms\I18nBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends EntityRepository
{
    public function getActiveAliases()
    {
        $queryBuilder = $this->createQueryBuilder('l')
            ->select('l.alias')
            ->where('l.enabled = 1');
        $rows = $queryBuilder->getQuery()->getArrayResult();
        return array_column($rows, 'alias');
    }
}
