OmCms\AdminBundle\Entity\User\User:
    type: entity
    table: fos_user_user
    repositoryClass: OmCms\AdminBundle\Entity\User\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
